version: '3.7'

services:

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    volumes:
      - './services/users:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_PROD_URL=postgres://postgres@users-db:5432/users_prod
      - DATABASE_QA_URL=postgres://postgres@users-db:5432/users_qa
      - DATABASE_DEV_URL=postgres://postgres@users-db:5432/users_dev
    depends_on: 
      - users-db
  
  users-db:
    build: 
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports: 
     - 5435:5432
    environment: 
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres