version: '3.7'

services:

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    volumes:
      - './services/users:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_PROD_URL=postgres://postgres:postgres@users-db:5432/users_prod
      - DATABASE_QA_URL=postgres://postgres:postgres@users-db:5432/users_qa
      - DATABASE_DEV_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - SECRET_KEY=mysupersecretkey
    depends_on: 
      - users-db
  
  users-db:
    build: 
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports: 
     - 5435:5432
    environment: 
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    volumes:
      - './services/web:/usr/src/app'
      - /usr/src/app/node_modules
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - users
  
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfileprod
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - web